Update DAY-02.md
AbhiTheModder/understand-smali pull request #2
Opened 2024-02-23 20:01 UTC by BhavanVidya

Hehe boi 😉

2024-02-23 20:06 UTC, AbhiTheModder requested changes
¯⁠\⁠_⁠ಠ⁠_⁠ಠ⁠_⁠/⁠¯

2024-02-23 20:06 UTC, AbhiTheModder commented on DAY-02.md
> +_So I left some things on DAY 01 because I don't you to forget the things and that's why left in middle so when I start from left part you need to recall previous ones_
😑😑

2024-02-23 20:06 UTC, AbhiTheModder commented on DAY-02.md
> +_So I left some things on DAY 01 because I don't you to forget the things and that's why left in middle so when I start from left part you need to recall previous ones_
If you want to modify it like this then it should be "don't want"

2024-02-23 20:11 UTC, AbhiTheModder requested changes

2024-02-23 20:11 UTC, AbhiTheModder commented on DAY-02.md
> -  - The _void type does the work like an end method as we say that method is codes starting parent and .end method is it's ending he same way void type represent the void return type as a class and c
Wrong!

2024-02-23 20:11 UTC, AbhiTheModder commented on DAY-02.md
> -    so, first talk about registers
Could you please modify this to "So, let's first talk about registers"

2024-02-23 20:11 UTC, AbhiTheModder commented on DAY-02.md
> +**Now I've told every basic thing, for further understanding you should consider reading the smali grammar table. Don't learn the table. Each time you're modifying any application, have a look on the
Instead of "You'll find ..." Please correct it to "You can find..."

2024-02-23 20:11 UTC, AbhiTheModder commented on DAY-02.md
> +_**But the resultss don't seem interesting to me, so I'll try to search for the words separately**_
extra "s" in results

2024-02-23 20:42 UTC, IndAlok reviewed
:)

2024-02-23 20:45 UTC, BhavanVidya reviewed
maybe done :)

2024-02-23 20:58 UTC, AbhiTheModder requested changes

2024-02-23 20:58 UTC, AbhiTheModder commented on DAY-02.md
> +  - The _void type works like an end method. Just like we say that `.method` is codes(in Smali a method directive) starting parent notation, the `.end` method is it's ending,  similarly, void type re
In Smali end mothid line js concatenated as `.end method`

2024-02-24 02:41 UTC, AbhiTheModder approved these changes

2024-02-24 02:41 UTC, merged