Update DAY-04.md
AbhiTheModder/understand-smali pull request #4
Opened 2024-02-23 22:20 UTC by BhavanVidya

t.me is blocked in some regions, telegram.me is better :)

2024-02-24 02:47 UTC, AbhiTheModder requested changes

2024-02-24 02:47 UTC, AbhiTheModder commented on DAY-04.md
> +3. It's always recommended to first check the opening actvity of any app during reverse engineering of it for many reasons, such as, checking what is it doing on run, and sometimes devs leave their i
Instead of "guys need" it's better to use "are in need of"

2024-02-24 03:51 UTC, BhavanVidya reviewed
:)

2024-02-25 02:18 UTC, AbhiTheModder approved these changes

2024-02-25 02:18 UTC, merged