Update DAY-5.md
AbhiTheModder/understand-smali pull request #5
Opened 2024-02-23 22:45 UTC by BhavanVidya

😶

2024-02-24 02:51 UTC, AbhiTheModder requested changes

2024-02-24 02:51 UTC, AbhiTheModder commented on DAY-5.md
> +or MT could do this too sometimes:
OR is used uppercase fir a sense of highlight here don't lower it

2024-02-24 03:54 UTC, BhavanVidya reviewed
;)

2024-02-25 02:19 UTC, AbhiTheModder approved these changes

2024-02-25 02:19 UTC, merged